[package]
name = "bdk-ext"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bdk = { version = "0.21.0", default-features = false, features = ["key-value-db"] }
rand = "0.6"
secp256k1 = { version = "0.22", features = ["rand", "global-context-less-secure"] }
