[package]
name = "daemon"
version = "0.4.2"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1.52"
bdk = { version = "0.16", default-features = false, features = ["electrum"] }
bdk-ext = { path = "../bdk-ext" }
bytes = "1"
cached = { version = "0.30.0", default-features = false, features = ["proc_macro"] }
futures = { version = "0.3", default-features = false, features = ["std"] }
hkdf = "0.12"
maia = "0.1.0"
model = { path = "../model" }
parse-display = "0.5.3"
rand = "0.6"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls-webpki-roots"] }
rust_decimal = { version = "1.21", features = ["serde-with-float"] }
rust_decimal_macros = "1.21"
semver = { version = "1.0.5", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = { version = "1", features = ["macros"] }
sha2 = "0.10"
snow = "0.9"
sqlx = { version = "0.5", features = ["offline", "sqlite", "uuid", "runtime-tokio-rustls"] }
thiserror = "1"
time = { version = "0.3", features = ["serde", "macros", "parsing", "formatting", "serde-well-known"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "net"] }
tokio-tasks = { path = "../tokio-tasks" }
tokio-util = { version = "0.6", features = ["codec"] }
tracing = { version = "0.1" }
uuid = { version = "0.8", features = ["serde", "v4"] }
x25519-dalek = { version = "1.1" }
xtra = { version = "0.6" }
xtra-bitmex-price-feed = { path = "../xtra-bitmex-price-feed" }
xtra_productivity = { version = "0.1.0" }
xtras = { path = "../xtras" }

[dev-dependencies]
pretty_assertions = "1"
serde_test = "1"
time = { version = "0.3", features = ["std"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "env-filter", "tracing-log"] }
