[package]
name = "daemon"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
async-trait = "0.1.51"
atty = "0.2"
bdk = { version = "0.12", default-features = false, features = ["sqlite", "electrum"] }
bytes = "1"
cfd_protocol = { path = "../cfd_protocol" }
clap = "3.0.0-beta.4"
futures = { version = "0.3", default-features = false }
hex = "0.4"
hkdf = "0.11"
itertools = "0.10"
nalgebra = { version = "0.29", default-features = false, features = ["std"] }
ndarray = "0.15.3"
ndarray_einsum_beta = "0.7.0"
num = "0.4.0"
rand = "0.6"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls-webpki-roots"] }
rocket = { version = "0.5.0-rc.1", features = ["json"] }
rocket-basicauth = { version = "2", default-features = false }
rocket_db_pools = { git = "https://github.com/SergioBenitez/Rocket", features = ["sqlx_sqlite"] }
rust-embed = "6.2"
rust_decimal = { version = "1.16", features = ["serde-float", "serde-arbitrary-precision"] }
rust_decimal_macros = "1.16"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_plain = "1"
serde_with = { version = "1", features = ["macros"] }
sha2 = "0.9"
sqlx = { version = "0.5", features = ["offline"] }
thiserror = "1"
time = { version = "0.3", features = ["serde"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "net"] }
tokio-tungstenite = { version = "0.15", features = ["rustls-tls"] }
tokio-util = { version = "0.6", features = ["codec"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.2", default-features = false, features = ["fmt", "ansi", "env-filter", "chrono", "tracing-log", "json"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
xtra = { version = "0.6", features = ["with-tokio-1"] }

[[bin]]
name = "taker"
path = "src/taker.rs"

[[bin]]
name = "maker"
path = "src/maker.rs"

[dev-dependencies]
pretty_assertions = "1"
tempfile = "3"
time = { version = "0.3", features = ["std"] }
